### ISSUE TITLE
Logysia does not work with Elysia v1 due to breaking changes

### ISSUE THREAD

**Issue by cybercoder-naj** [tristanisham/logysia#11]
As for the Elysia v1.0.0-rc.11, there are breaking changes which also break logysia in the process. Refer [elysiajs/elysia#513](https://github.com/elysiajs/elysia/issues/513) to know more

**Comment by tristanisham** [comment]
Merged.

**Comment by Yashrocky96** [comment]
@tristanisham Please release it as well? Or how do I use this latest changes?
