### ISSUE TITLE
Output showing in s (Seconds) instead of micro or milli seconds And Output not in readable format

### ISSUE THREAD

**Issue by Yashrocky96** [tristanisham/logysia#4]
Added an Image to show the output

In the first you can see it's showing "s" which is not correct

And in the second log it's not in a readable format

<img width="284" alt="image" src="https://github.com/tristanisham/logysia/assets/16666637/19687698-0a9b-4bb7-af9e-37e571484a80">

Request:-
1. Add a UTC timestamp as a configurable option maybe because we can stream these logs or access from Docker logs we would be able to confirm with a timestamp

**Comment by kareemmahlees** [comment]
Hi 👋 , it this is accepted I would like to work on this, could you assign it to me 🙂!

**Comment by tristanisham** [comment]
Okay, I will take a look at it. The timing got messed up in the last update from a bug I didn't catch. 

I could include that. Maybe a few other logging options too like JSON for structured loggers?

**Comment by Yashrocky96** [comment]
@tristanisham 

Logger does look good and this will help a lot in future.

You can provide more options, also you can maybe as well use local timestamp so that people developing in their own timezone will be able to relate by the time easier. You can enable this as an option.

What do you have in mind for Structured loggers?

Also are you working on adding testing?

**Comment by tristanisham** [comment]
@Yashrocky96 could you make a pull request for the errant seconds label? 

As for logging, I'll add some options to enable logging in UTC and support for the TZ variable.

**Comment by Yashrocky96** [comment]
@tristanisham I have raised a PR, Please review and let me know

**Comment by tristanisham** [comment]
#5 is almost done. One more change and it's good to merge @Yashrocky96

**Comment by Yashrocky96** [comment]
@tristanisham I have updated the PR

Also, Please check this out if you can.

Story:- When there's an error during execution of onError for example during development you are giving a wrong JSON and you get an error that the input is Failed to parse JSON.

In this scenario, onError hook is executing twice and logging the information twice.

For now, I am fairly new with Elysia and do not understand why that is happening.

**Comment by Yashrocky96** [comment]
@tristanisham Please close this issue and would I not join as a Contributor here?

Also please do a patch release, as the logging is not in a working condition.

**Comment by Yashrocky96** [comment]
@tristanisham

**Comment by tristanisham** [comment]
Hi,

I am on vacation and will review these changes when I return in
November. 

Tristan Isham

On October 23, 2023, Tristan Isham ***@***.***> wrote:
> @tristanisham <https://github.com/tristanisham>
>

—
Reply to this email directly, view it on GitHub
<https://github.com/tristanisham/logysia/issues/4#issuecomment-
1774702710>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AFQNWUQIXLSLPUOWAMZVWC3YAYUTJAVCNFSM6AAAAAA5VUOQ4GVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTONZUG4YDENZRGA>.
You are receiving this because you were mentioned.Message ID:
***@***.***>

**Comment by Yashrocky96** [comment]
Hi Tristanisham,

Hope that you are back from your vacations, Would you please add me as a contributor and do a patch release please?

**Comment by tristanisham** [comment]
Could you please send them here?

**Comment by Yashrocky96** [comment]
> Could you please send them here?
What do I send and how do I send, This is my first Open-Source Contribution @tristanisham . Please guide me. And thanks.

You have already merged my changes from my forked repository

**Comment by Yashrocky96** [comment]
Hi @tristanisham Please do a patch release and add me as a contributor to the package, if my application does use this package.

**Comment by Yashrocky96** [comment]
@tristanisham Please do a patch release
