### ISSUE TITLE
Declare Elysia as peer dependency

### ISSUE THREAD

**Issue by antlanc7** [tristanisham/logysia#6]
Everytime I upgrade Elysia in my project, seems like the plugin keeps a separate outdated Elysia dependency in its own dependency tree.
I think declaring Elysia as peer dependency, in order to depend on the user project Elysia version, would fix it.

**Comment by tristanisham** [comment]
Good idea. Will do.

**Comment by tristanisham** [comment]
Okay, in the latest release
